"""Add pricing tier to User model

Revision ID: 0648887b9978
Revises: 87667dbe7833
Create Date: 2025-03-11 20:37:44.097924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0648887b9978'
down_revision = '87667dbe7833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_tier', sa.String(), nullable=True))
    
    # Step 2: Update existing rows with default value 'hobby'
    op.execute("UPDATE users SET pricing_tier = 'hobby' WHERE pricing_tier IS NULL")
    
    # Step 3: Make the column non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pricing_tier', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pricing_tier')

    # ### end Alembic commands ###
