"""Add click_count and last_accessed_at columns

Revision ID: 4b1344b7b059
Revises: 
Create Date: 2025-02-21 19:12:42.711000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1344b7b059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('click_count')

    # ### end Alembic commands ###
