"""Add timeout_seconds to URL model

Revision ID: 87667dbe7833
Revises: 3a6c09e5b7ca
Create Date: 2025-03-10 19:50:54.574674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87667dbe7833'
down_revision = '3a6c09e5b7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_column('timeout_seconds')

    # ### end Alembic commands ###
